version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 9
    schedule:
      interval: "monthly"
